### ISSUE TITLE
LMC FE Strip Lights not visible

### ISSUE THREAD

**Issue by itarampoulous** [fireescapefilms/fireescapefilms.github.io#13]
![image](https://github.com/user-attachments/assets/a5e3563b-357d-4e94-b8fe-8504281b3779)

![image](https://github.com/user-attachments/assets/89036460-891e-43cc-a568-48a18b3626cb)

The FE Strip Lights are not visible to book.

**Comment by legendPerceptor** [comment]
I changed the bundle to be visible. I am not exactly sure if the strip light is well organized in the cage. It might be hard for cage staff to find it. You can check it out and test it maybe.

**Comment by itarampoulous** [comment]
I now see it but I still cannot add it to a reservation for some reason.

**Comment by legendPerceptor** [comment]
I just checked and it has no problems on my side.

<img width="962" alt="Screenshot 2024-10-29 at 3 12 42 PM" src="https://github.com/user-attachments/assets/0aec5fa8-b681-4933-8f16-14bedd426010">

**Comment by itarampoulous** [comment]
Alright. It now works. Thanks
