### ISSUE TITLE
Access group inconcistency

### ISSUE THREAD

**Issue by itarampoulous** [fireescapefilms/fireescapefilms.github.io#3]
I am in the advanced group access and I have access to the Sony A7SIII bundles but not the chargers that come with them (in the same bundle). There must be some inconsistency in how access is granted.

**Comment by legendPerceptor** [comment]
I just updated the authorization of the charger. It required authorization but was not assigned to a proper group. Now all the Sony  A7s3 items should be in FE General Access group and you should have access to the bundle.

**Comment by legendPerceptor** [comment]
The access group problem issue has been resolved, and I will close this issue.
