### ISSUE TITLE
The new V-mount battery kit missing

### ISSUE THREAD

**Issue by legendPerceptor** [fireescapefilms/fireescapefilms.github.io#4]
We have two new bundles of V-mount batteries but they are not there in the Patron Portal.

![image](https://github.com/user-attachments/assets/96d6e8ec-ca67-4a25-b3dc-4f811fa05241)

According to [our website](https://fireescapefilms.org/equipment/), there should be a V-Mount battery bundle. Please solve this issue.

**Comment by legendPerceptor** [comment]
From the WebCheckout, we have a bunch of V-Mount batteries, but a lot of them are out of service. We only have 2 old V-mount batteries that are working.

![image](https://github.com/user-attachments/assets/b2d76df9-586f-4cb2-ab25-97a2d1bde401)

We should build another resource type for our new batteries. Each bag has two V-mount batteries and a charger. Make them a bundle.

**Comment by anarcosudaca** [comment]
V-Mount bundle has been created successfully. Old batteries should be moved to the graveyard once identified. Now, only the new stuff (in the bundles) is accessible until the old and working standalone v-mount batteries can be singled out.
