### ISSUE TITLE
New tags need to be printed and attached

### ISSUE THREAD

**Issue by legendPerceptor** [fireescapefilms/fireescapefilms.github.io#7]
We've made a list of new tags to be printed and attached to bags. Someone needs to print them as soon as possible and take them to the cage. The designing/printing has been postponed for months. Without tags, it can be very hard for the cage staff to find items.

[x2]
SONY A7S3 Camera Kit
- SONY A7S3 Camera Body
- Len Adaptor
- Battery Charger
- [x2] 128GB SD card

[x1]
SONY A7M4 Camera Kit
- SONY A7M4 Camera Body
- Len Adaptor
- Battery Charger
- [x2] 128GB SD card

[x1]
Blackmagic Camera 6K Pro
**WRONG**  See replies below for this kit.
- Camera body
- Top Handle
- Side Handle
- Camera Strip
- Battery Charger
- Camera Charger
- XLR to mini-XLR

[x2]
G-Drive 4 TB
- G-Drive body
- G-Drive data cable
- G-Drive Power supply

[x1]
G-Drive 6 TB
- G-Drive body
- G-Drive data cable
- G-Drive Power supply

[x1]
SONY 24-70mm f/2.8 Lens
- A lens body
- A lens cap
- A lens Hood

[x1]
Rhino Armor Manual Slider

[x1]
Flycam Redking Vest

[x1]
Hollyland Mars 300 Video Transmission System
- Receiver
- Transmitter
- 3 Antennas
- A camera mount
- A base plate

[x1]
Rokinon 100m f/2.8 Lens

[x2]
Atomos Ninja V Monitor
- Monitor
- 500GB SSD Drive
- Drive USB cable

[x1]
GVM Electronic Slider
- The slider main body
- A controller
- A tripod head
- Cables

[x1]
Sigma 100-400m f5-f6.3 Lens
- Lens body
- Lens cap
- Lens hood

[x1]
Dolly-only tripod kit
- Libec Dolly
- Sachtler Ace tripod

**Comment by anarcosudaca** [comment]
The BMPCC Tags are wrong. The correct ones are these:

BMPCC 6k (x1):

- BMPCC 6K Body
- BMPCC 6K Base Plate (Tilta)
- BMPCC 6K Top Handle (Tilta)
- BMPCC 6K Side Handle (Tilta)
- BMPCC 6K V-Mount Adapter
- BMPCC 6K Side Handle Power Cable
- BMPCC 6K Micro XLR Adapter Cable
- BMPCC 6K AC Power Adapter
- BMPCC 6K Rods (2x)
- BMPCC 6K Battery Charger
- BMPCC 6K Battery Charger Cable

BMPCC 6K PRO (x1):

- BMPCC 6K Pro Body 
- BMPCC 6K Pro Top Handle (SmallRig)
- BMPCC 6K Pro Side Handle (SmallRig)
- BMPCC 6K Pro V-Mount Adapter
- BMPCC 6K Pro V-Mount Adapter Cable
- BMPCC 6K Pro Micro XLR Adapter Cable
- BMPCC 6K Pro AC Power Adapter
- BMPCC 6K Pro Rods (2x)
- BMPCC 6K Pro Battery Charger
- BMPCC 6K Pro Battery Charger Cable

**Comment by anarcosudaca** [comment]
Tags have been added.
