### ISSUE TITLE
Items with barcodes but not added to the system

### ISSUE THREAD

**Issue by legendPerceptor** [fireescapefilms/fireescapefilms.github.io#9]
During today's return, I identified some barcode problems that have been ignored in the past. We should add them to the system and in the correct bundle so cage staff will not get an error when scanning them.

1. The GVM slider remote controller.

![IMG_9164](https://github.com/user-attachments/assets/934491ab-d224-44de-b0fe-e8b73581737a)

2. The DJI Gimbal Top Bar

![IMG_9165](https://github.com/user-attachments/assets/2d381e52-e14d-470e-90cf-5986f172afec)

3. Atomos Battery Charger

![IMG_9166](https://github.com/user-attachments/assets/e53c644e-1d49-4f0a-96ee-b82193c77a40)

4. The camera top mount of Hollyland Mars300. Let's just call it `Mars300 Transmitter Mount`

![IMG_9168](https://github.com/user-attachments/assets/f5e166da-4990-4b80-aba9-80449337e3bd)

5. The camera strip for the Sony A7IV

![IMG_9169](https://github.com/user-attachments/assets/2b7cd174-61ea-46a4-8686-a756ebb3364f)

**Comment by anarcosudaca** [comment]
I'd like to put forward the question of - do the straps need to be barcoded?

**Comment by legendPerceptor** [comment]
The strip usually does not need a barcode, but we have this one barcoded. I've added all of them to the system.

**Comment by legendPerceptor** [comment]
This issue should have been solved. I added all of the mentioned items into the system and into the correct bundle.

The problem with the Atomos charger is that there is only one in one of the bags. So I did not include this into the bundle but put it as a `LMC FE Atomos Battery Charger Spare`. There won't be a problem for the cage staff to scan it, but it is just not in the bundle.

**Comment by legendPerceptor** [comment]
The issue is solved and I will close it.
